services:

  head:
    hostname: head
    container_name: head
    cpus: 5.0
    mem_limit: 5g
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp:/tmp:rw
    environment:
      - SLURM_CPUS_ON_NODE=1
    ports:
      - 6817:6817
      - 6818:6818
