name: Build and Publish Docker SLURM Accounting Image

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build the Docker image Ubuntu22-slurm-accounting
        run:  docker build images/ubuntu22-slurm-accounting --tag ghcr.io/fractal-analytics-platform/ubuntu22-slurm-accounting:0.1
      - name: Push Docker Image
        run: docker push ghcr.io/fractal-analytics-platform/ubuntu22-slurm-accounting:0.1