name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN  }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          run: |
                docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
                docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
                docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
