name: Build and Publish OAuth Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image OAuth
        run:  docker build images/oauth --tag ghcr.io/fractal-analytics-platform/oauth:0.1

      - name: Push Docker Image
        run: docker push ghcr.io/fractal-analytics-platform/oauth:0.1
