name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 23 * * 2,3,4"

jobs:

  tests-v1:
    timeout-minutes: 20
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Update .env file
      run: sed -i 's/^FRACTAL_RUNNER_BACKEND=local_experimental$/FRACTAL_RUNNER_BACKEND=local/' ./server/server.env
    
    - name: Run demos
      run: make run-demos-v1-github

  tests-v2:
    timeout-minutes: 20
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run demos
      run: make run-demos-v2-github
