name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run demos
      run: make run-demos-github
