name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 23 * * 2,3,4"

jobs:
  tests:
    timeout-minutes: 21
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run demos
      run: make run-demos-github
