name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 23 * * 2,3,4"

jobs:

  tests-v1:
    timeout-minutes: 20
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache SLURM Docker images
      id: cache-docker-ubuntu22-slurm-tasks-core
      uses: actions/cache@v4
      with:
        path: ci/cache/docker/ubuntu22-slurm-tasks-core
        key: cache-docker-ubuntu22-slurm-tasks-core

    - name: Use SLURM Docker Image Cache if cache hit
      if: steps.cache-docker-ubuntu22-slurm-tasks-core.outputs.cache-hit == 'true'
      run: docker image load --input ./ci/cache/docker/ubuntu22-slurm-tasks-core/ubuntu22-slurm-tasks-core.tar

    - name: Update SLURM Docker Image Cache if cache miss
      if: steps.cache-docker-ubuntu22-slurm-tasks-core.outputs.cache-hit != 'true'
      run: docker pull ghcr.io/fractal-analytics-platform/ubuntu22-slurm-tasks-core:0.1 && mkdir -p ci/cache/docker/ubuntu22-slurm-tasks-core && docker image save ghcr.io/fractal-analytics-platform/ubuntu22-ubuntu22-slurm-tasks-core:0.1 --output ./ci/cache/docker/ubuntu22-slurm-tasks-core/ubuntu22-slurm-tasks-core.tar

    - name: Set FRACTAL_RUNNER_BACKEND to 'slurm'
      run: sed -i 's/local_experimental$/local/' ./testing/server/server.env

    - name: Run demos
      run: cd testing && make run-demos-v1-github

  tests-v2:
    timeout-minutes: 20
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache SLURM Docker images
      id: cache-docker-ubuntu22-slurm-tasks-core
      uses: actions/cache@v4
      with:
        path: ci/cache/docker/ubuntu22-slurm-tasks-core
        key: cache-docker-ubuntu22-slurm-tasks-core

    - name: Use SLURM Docker Image Cache if cache hit
      if: steps.cache-docker-ubuntu22-slurm-tasks-core.outputs.cache-hit == 'true'
      run: docker image load --input ./ci/cache/docker/ubuntu22-slurm-tasks-core/ubuntu22-slurm-tasks-core.tar

    - name: Update SLURM Docker Image Cache if cache miss
      if: steps.cache-docker-ubuntu22-slurm-tasks-core.outputs.cache-hit != 'true'
      run: docker pull ghcr.io/fractal-analytics-platform/ubuntu22-slurm-tasks-core:0.1 && mkdir -p ci/cache/docker/ubuntu22-slurm-tasks-core && docker image save ghcr.io/fractal-analytics-platform/ubuntu22-ubuntu22-slurm-tasks-core:0.1 --output ./ci/cache/docker/ubuntu22-slurm-tasks-core/ubuntu22-slurm-tasks-core.tar

    - name: Run demos
      run: cd testing && make run-demos-v2-github
