name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 23 * * 2,3,4"

jobs:

  tests-v1:
    timeout-minutes: 20
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set FRACTAL_RUNNER_BACKEND to 'local'
      run: sed -i 's/local_experimental$/local/' ./testing/server/server.env

    - name: Run demos
      run: cd testing && make run-demos-v1-github

  tests-v2:
    timeout-minutes: 20
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run demos
      run: cd testing && make run-demos-v2-github
