name: Test

on: workflow_dispatch

jobs:
  tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start containers
      run: docker compose --file docker-compose-demos.yml up --build --force-recreate
